import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s - Create Next App",
    // absolute: '"Create Next App"',
  },
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh] flex flex-col `}
      >
        <header className="w-full flex items-start h-20 bg-red-500 text-white ">
          <h1>Header</h1>
        </header>
        <main className="flex-grow">{children}</main>
        <footer className="w-full flex items-end  h-20 bg-blue-500 text-white">
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
